import { Product } from '@models/product';
import { Milestone } from '@models/milestone';
import { Financial } from '@models/financial';
import { Detail } from '@models/detail';
import { FinancialIndicator } from '@models/financialIndicator';
import { DetailInformation } from '@models/detailInformation';

export interface Initiative {
    id: number;
    initiativeCode: string;
    name: string;
    year: string;
    ownerName: string;
    organization: string;
    company: string;
    specifyCompany: string;
    plant: string;
    specifyPlant: string;
    location: string;
    specifyLocation: string;
    registeringDate: Date;
    startingDate: Date;
    finishingDate: Date;
    background: string;
    resultObjective: string;
    initiativeType: string;
    requestCapex: string;
    typeOfInvestment: string;
    involveItDigital: number;
    requestProjectEngineer: number;
    budgetType: string;
    ram: string;
    jFactor: number;
    irr: number;
    costEstCapex: number;
    costEstCapexType: string;
    divestment: number;
    budgetSource: string;
    requestOpex: string;
    costEstOpex: number;
    costEstOpexType: string;
    typeBenefit: string;
    benefitAmount: number;
    benefitAmountType: string;
    payBackPeriod: number;
    fxExchange: number;
    cim: number;
    pim: number;
    dim: number;
    max: number;
    directCapex: number;
    cpi: number;
    strategy: number;
    randD: number;
    other: number;
    trackMax: number;
    createdDate: Date;
    createdBy: string;
    updatedDate: Date;
    updatedBy: string;
    approvedDate: Date;
    lastActivity: Date;
    status: string;
    remark: string;
    stage: string;
    attachments: [];
    initiativeCoDevelopers: [];
    initiativeDetails: Detail;
    products: Product;
    milestones: Milestone;
    detailInformations: DetailInformation;
    financialIndicators: FinancialIndicator;
    financials: Financial;
    initiativeId: number;
    itDigital: string;
}


