// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTT_GC_API.Data;

namespace PTT_GC_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200331070235_StageInitiative")]
    partial class StageInitiative
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PTT_GC_API.Models.BuWorkstream.BuWorkstream", b =>
                {
                    b.Property<string>("BuWorkstreamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuWorkstreamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuWorkstreamId");

                    b.ToTable("BuWorkstreams");
                });

            modelBuilder.Entity("PTT_GC_API.Models.CoDeveloper.CoDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoDeveloperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoDevelopers");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.DetailInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComparisonWithOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorporateImageIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepreciationCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EbitdaBaseCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EbitdaOptimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EbitdaPessimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("IL3Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IL4Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IL5Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("InitiativeTypeMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiativeYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeySuccessFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketOverview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NpvBaseCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NpvOptimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NpvPessimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OptimisticCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherBusiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInvestment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherStrategic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaybackBaseCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaybackOptimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaybackPessimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PessimisticCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PotentialCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProLever")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProSubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProjectIrrBaseCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProjectIrrOptimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProjectIrrPessimisticCase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafetyIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceOfFeedstock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorEvp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategicObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubWorkstream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SynergyBenefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsefulLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workstream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstreamLead")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DetailInformations");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FrequencyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.InitiativeTypeMax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InitiativeTypeMaxTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InitiativeTypeMaxs");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.KpiDetailInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Kpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("KpiDetailInformations");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.Kpis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KpisTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kpises");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.SubWorkstream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubWorkstreamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkStreamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubWorkstreams");
                });

            modelBuilder.Entity("PTT_GC_API.Models.EntryMode.EntryMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntryModeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryModeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntryModes");
                });

            modelBuilder.Entity("PTT_GC_API.Models.ImpactTracking.ImpactTypeOfBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImpactTypeOfBenefitTable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Month1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month11")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month13")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month14")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month15")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month16")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month17")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month19")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month21")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month22")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month23")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month24")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month25")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month26")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month27")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month28")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month29")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month30")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month31")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month32")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month33")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month34")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month35")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month36")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Month9")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RunRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeOfBenefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("ImpactTypeOfBenefits");
                });

            modelBuilder.Entity("PTT_GC_API.Models.ImpactTracking.ShareBenefitWorkstream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImpactTrackingId")
                        .HasColumnType("int");

                    b.Property<string>("Workstream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("percent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShareBenefitWorkstreams");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Financial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AvgEbitda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCapex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalOpex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalValuation")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId")
                        .IsUnique();

                    b.ToTable("Financials");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.FinancialIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Capex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Opex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Valuation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("FinancialIndicators");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.ImpactTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutoCalculate")
                        .HasColumnType("bit");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("FinancialImpactArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstRunRateMonth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HaveShareBenefit")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IL4ActualPriceFixedFx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IL4RunRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IL5ActualPriceFloatFx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IL5RunRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ImpiemantCost")
                        .HasColumnType("bit");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Remark1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToComment")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId")
                        .IsUnique();

                    b.ToTable("ImpactTrackings");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("BenefitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BenefitAmountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuWorkStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Cim")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CostEstCapex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Cpi")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DeletedFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<bool?>("Dim")
                        .HasColumnType("bit");

                    b.Property<bool?>("DirectCapex")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinishingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FxExchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InitiativeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiativeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Irr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool?>("Max")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Other")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PayBackPeriod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Pim")
                        .HasColumnType("bit");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RandD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegisteringDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("RequestCapex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultObjective")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("SpecifyLocation")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Strategy")
                        .HasColumnType("bit");

                    b.Property<string>("TypeBenefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfInvestment")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Wacc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costEstCapexType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.InitiativeCoDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoDeveloperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("InitiativeCoDevelopers");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.InitiativeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntryMode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FX")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("FirstBudgetYear")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("FxChoice")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("HaveProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("PlanBOD1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanBOD2")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ShareOfInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StrategicObjective")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("StrategyDetail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId")
                        .IsUnique();

                    b.ToTable("InitiativeDetails");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("KeyDeliverable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Milestone.MilestoneStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MilestoneStatusId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MilestoneStatuses");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Owner.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Plant.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Product.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductUnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUnitTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Strategy.StrategicObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StrategicObjectiveCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategicObjectiveTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StrategicObjectives");
                });

            modelBuilder.Entity("PTT_GC_API.Models.Strategy.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StrategicObjectiveId")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StrategicObjectiveId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("PTT_GC_API.Models.TypeOfBenefit.TypeOfBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfBenefitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBenefitGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBenefitTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfBenefits");
                });

            modelBuilder.Entity("PTT_GC_API.Models.TypeOfInvestment.TypeOfInvestment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfInvestmentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfInvestmentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfInvestments");
                });

            modelBuilder.Entity("PTT_GC_API.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Approver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PTT_GC_API.Models.WorkStream.WorkStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WorkStreamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkStreams");
                });

            modelBuilder.Entity("PTT_GC_API.Models.DetailInformation.KpiDetailInformation", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("KpiDetailInformations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.ImpactTracking.ImpactTypeOfBenefit", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("ImpactTypeOfBenefits")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Attachment", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("Attachments")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Financial", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithOne("Financials")
                        .HasForeignKey("PTT_GC_API.Models.Initiative.Financial", "InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.FinancialIndicator", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("FinancialIndicators")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.ImpactTracking", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithOne("ImpactTrackings")
                        .HasForeignKey("PTT_GC_API.Models.Initiative.ImpactTracking", "InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.InitiativeCoDeveloper", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("InitiativeCoDevelopers")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.InitiativeDetail", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithOne("InitiativeDetails")
                        .HasForeignKey("PTT_GC_API.Models.Initiative.InitiativeDetail", "InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Milestone", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("Milestones")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Initiative.Product", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Initiative.Initiative", null)
                        .WithMany("Products")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTT_GC_API.Models.Strategy.Strategy", b =>
                {
                    b.HasOne("PTT_GC_API.Models.Strategy.StrategicObjective", null)
                        .WithMany("Strategies")
                        .HasForeignKey("StrategicObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
